-- Final Optimized Studio Private Lessons Table Design
-- Removes redundant LESSON_DATA column - all data is in FULL_WEEK_JSON.schedule

-- Drop existing table
DROP TABLE STUDIO_PRIVATE_LESSONS;

-- Drop existing view
DROP VIEW V_STUDIO_LESSONS;

-- Create final optimized table
CREATE TABLE STUDIO_PRIVATE_LESSONS (
    LESSON_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WEEK_START_DATE DATE NOT NULL,
    WEEK_IDENTIFIER VARCHAR2(50) NOT NULL,
    SHEET_NAME VARCHAR2(100) NOT NULL,
    FULL_WEEK_JSON CLOB NOT NULL CHECK (FULL_WEEK_JSON IS JSON),
    EXTRACTED_DATE DATE DEFAULT SYSDATE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_DATE DATE DEFAULT SYSDATE
);

-- Create indexes for better performance
CREATE INDEX idx_studio_lessons_week ON STUDIO_PRIVATE_LESSONS(week_identifier);
CREATE INDEX idx_studio_lessons_sheet ON STUDIO_PRIVATE_LESSONS(sheet_name);

-- Create functional indexes for common JSON queries
CREATE INDEX idx_studio_lessons_schedule ON STUDIO_PRIVATE_LESSONS(
    JSON_EXISTS(FULL_WEEK_JSON, '$.schedule[*]')
);

-- Add comments
COMMENT ON TABLE STUDIO_PRIVATE_LESSONS IS 'Store private lesson schedules - all data in FULL_WEEK_JSON';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_start_date IS 'Start date of the week (e.g., 2025-06-09)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_identifier IS 'Unique identifier for the week (e.g., 2025-06-09-69-615)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.sheet_name IS 'Excel sheet name (e.g., 69-615)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.full_week_json IS 'Complete JSON: schedule array, teachers, studios, metadata';

-- Create view that flattens time slots for easy querying
CREATE OR REPLACE VIEW V_STUDIO_TIME_SLOTS AS
SELECT 
    sl.LESSON_ID,
    sl.WEEK_START_DATE,
    sl.WEEK_IDENTIFIER,
    sl.SHEET_NAME,
    jt.time_slot,
    jt.lessons_json,
    sl.EXTRACTED_DATE,
    sl.CREATED_DATE,
    sl.MODIFIED_DATE
FROM STUDIO_PRIVATE_LESSONS sl,
     JSON_TABLE(sl.FULL_WEEK_JSON, '$.schedule[*]'
         COLUMNS (
             time_slot VARCHAR2(10) PATH '$.time',
             lessons_json CLOB FORMAT JSON PATH '$.lessons'
         )
     ) jt;

-- Create view for individual lessons (fully flattened)
CREATE OR REPLACE VIEW V_STUDIO_LESSONS_DETAIL AS
SELECT 
    sl.LESSON_ID,
    sl.WEEK_START_DATE,
    sl.WEEK_IDENTIFIER,
    sl.SHEET_NAME,
    jt.time_slot,
    jt.lesson_day,
    jt.lesson_date,
    jt.studio,
    jt.student_info,
    jt.teacher,
    jt.teacher_color,
    sl.EXTRACTED_DATE
FROM STUDIO_PRIVATE_LESSONS sl,
     JSON_TABLE(sl.FULL_WEEK_JSON, '$.schedule[*]'
         COLUMNS (
             time_slot VARCHAR2(10) PATH '$.time',
             NESTED PATH '$.lessons[*]'
             COLUMNS (
                 lesson_day VARCHAR2(20) PATH '$.day',
                 lesson_date VARCHAR2(20) PATH '$.date',
                 studio VARCHAR2(20) PATH '$.studio',
                 student_info VARCHAR2(200) PATH '$.student_info',
                 teacher VARCHAR2(100) PATH '$.teacher',
                 teacher_color VARCHAR2(20) PATH '$.teacher_color'
             )
         )
     ) jt;

SELECT 'Final optimized STUDIO_PRIVATE_LESSONS table created successfully' AS result;
