-- Optimized Studio Private Lessons Table Design
-- Removes redundant TIME_SLOT column since time is in JSON data

-- Drop existing table
DROP TABLE STUDIO_PRIVATE_LESSONS;

-- Create optimized table
CREATE TABLE STUDIO_PRIVATE_LESSONS (
    LESSON_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WEEK_START_DATE DATE NOT NULL,
    WEEK_IDENTIFIER VARCHAR2(50) NOT NULL,
    SHEET_NAME VARCHAR2(100) NOT NULL,
    LESSON_DATA CLOB NOT NULL CHECK (LESSON_DATA IS JSON),
    FULL_WEEK_JSON CLOB NOT NULL CHECK (FULL_WEEK_JSON IS JSON),
    EXTRACTED_DATE DATE DEFAULT SYSDATE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_DATE DATE DEFAULT SYSDATE
);

-- Create indexes for better performance
CREATE INDEX idx_studio_lessons_week ON STUDIO_PRIVATE_LESSONS(week_identifier);
CREATE INDEX idx_studio_lessons_sheet ON STUDIO_PRIVATE_LESSONS(sheet_name);

-- Create functional index on JSON time field for fast time-based queries
CREATE INDEX idx_studio_lessons_time ON STUDIO_PRIVATE_LESSONS(
    JSON_VALUE(LESSON_DATA, '$.time')
);

-- Add comments
COMMENT ON TABLE STUDIO_PRIVATE_LESSONS IS 'Store private lesson schedules extracted from Excel files';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_start_date IS 'Start date of the week (e.g., 2025-06-09)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_identifier IS 'Unique identifier for the week (e.g., 2025-06-09-69-615)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.sheet_name IS 'Excel sheet name (e.g., 69-615)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.lesson_data IS 'JSON data containing all lessons for this time slot (includes time)';
COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.full_week_json IS 'Complete JSON object for the entire week schedule';

-- Create a view for easy querying with extracted time
CREATE OR REPLACE VIEW V_STUDIO_LESSONS AS
SELECT 
    LESSON_ID,
    WEEK_START_DATE,
    WEEK_IDENTIFIER,
    SHEET_NAME,
    JSON_VALUE(LESSON_DATA, '$.time') AS TIME_SLOT,
    LESSON_DATA,
    FULL_WEEK_JSON,
    EXTRACTED_DATE,
    CREATED_DATE,
    MODIFIED_DATE
FROM STUDIO_PRIVATE_LESSONS;

-- Grant permissions on the view
COMMENT ON VIEW V_STUDIO_LESSONS IS 'View with extracted time slot for easy querying';

SELECT 'Optimized STUDIO_PRIVATE_LESSONS table created successfully' AS result;
