-- Proper Studio Students Data
-- This file replaces the calendar import data with actual student records
-- Run this to clean up the incorrect data and add proper student records

-- First, clear out the calendar import data
DELETE FROM STUDIO_STUDENT_CLASSES WHERE STUDENT_ID IN (
    SELECT STUDENT_ID FROM STUDIO_STUDENTS WHERE NOTES LIKE '%Excel calendar%'
);

DELETE FROM STUDIO_ATTENDANCE WHERE STUDENT_ID IN (
    SELECT STUDENT_ID FROM STUDIO_STUDENTS WHERE NOTES LIKE '%Excel calendar%'
);

DELETE FROM STUDIO_SCHEDULE_SLOTS WHERE STUDENT_ID IN (
    SELECT STUDENT_ID FROM STUDIO_STUDENTS WHERE NOTES LIKE '%Excel calendar%'
);

DELETE FROM STUDIO_STUDENTS WHERE NOTES LIKE '%Excel calendar%';

-- Insert proper student records
INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Everly Hazard', 'Jennifer', 'Hazard', 'jenhaz23@gmail.com', '555-0101', DATE '2016-10-25', 'Both', 'Very dedicated student, loves contemporary and jazz', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Gemma Smith', 'Tia', 'Smith', 'TiaFSmith@gmail.com', '555-0102', DATE '2017-05-15', 'Both', 'Shows great potential in technique classes', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Hazel Vincent', 'Jaclyn', 'Vincent', 'jaclynvincent17@gmail.com', '555-0103', DATE '2017-10-22', 'Both', 'Excellent technique, natural ability for ballet', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Marik Bast', 'Amy', 'Bast', 'asbast5@gmail.com', '555-0104', DATE '2017-01-26', 'Both', 'Natural performer with strong stage presence', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Larkin Mack', 'Allison', 'Mack', 'allison0143@gmail.com', '555-0105', DATE '2016-04-29', 'Both', 'Strong solo work, excellent musicality', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Ronni Weiss', 'Adva', 'Weiss', 'Advaweiss@gmail.com', '555-0106', DATE '2010-07-28', 'Both', 'Senior level dancer, ready for advanced classes', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Mila Rodriguez', 'Carmen', 'Rodriguez', 'carmen.rodriguez@email.com', '555-0107', DATE '2018-03-12', 'Both', 'Beginner level, very enthusiastic about learning', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Reese Johnson', 'Michael', 'Johnson', 'mjohnson.dance@gmail.com', '555-0108', DATE '2015-08-09', 'Both', 'Advanced dancer, competing at national level', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Paige Thompson', 'Sarah', 'Thompson', 'sthompson.family@outlook.com', '555-0109', DATE '2014-11-17', 'Both', 'Strong in ballet and contemporary, needs work on jazz', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Ryann Foster', 'Kelly', 'Foster', 'kelly.foster.mom@gmail.com', '555-0110', DATE '2009-06-03', 'Both', 'Senior dancer, assistant teacher for younger classes', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Meghan Davis', 'Lisa', 'Davis', 'ldavis.dance@yahoo.com', '555-0111', DATE '2009-12-21', 'Both', 'Scholarship student, exceptional talent', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Caralin Wilson', 'Amanda', 'Wilson', 'awilson.dancer@gmail.com', '555-0112', DATE '2013-09-14', 'Both', 'Future ballet teacher, studying pedagogy', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Jacquelyn Martinez', 'Rosa', 'Martinez', 'rosa.martinez.family@gmail.com', '555-0113', DATE '2014-01-30', 'Both', 'Strong technical foundation, working on artistry', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Kinley Griffin', 'Rebecca', 'Griffin', 'bgriffin.mom@hotmail.com', '555-0114', DATE '2019-04-05', 'Both', 'Young dancer with natural rhythm', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Gracie Lee', 'Jennifer', 'Lee', 'jlee.dancer@icloud.com', '555-0115', DATE '2016-07-18', 'Both', 'Intermediate level, loves hip hop and jazz', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Remi Chen', 'David', 'Chen', 'dchen.family@gmail.com', '555-0116', DATE '2014-05-22', 'Both', 'Competitive dancer, multiple regional titles', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Charlotte Brown', 'Emily', 'Brown', 'ebrown.dance@gmail.com', '555-0117', DATE '2020-02-11', 'Both', 'Preschool dancer, loves creative movement', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Millie Taylor', 'Jessica', 'Taylor', 'jtaylor.kidsdance@outlook.com', '555-0118', DATE '2017-08-07', 'Both', 'Elementary level, great attitude and work ethic', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Stella Anderson', 'Nicole', 'Anderson', 'nanderson.mom@yahoo.com', '555-0119', DATE '2008-10-16', 'Both', 'Senior dancer, planning to pursue dance in college', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Georgia White', 'Michelle', 'White', 'mwhite.family@gmail.com', '555-0120', DATE '2008-03-29', 'Both', 'Advanced level, strong in all styles', 'SYSTEM');

-- Enroll some students in classes
-- Technique Intensive enrollments
INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Gemma Smith' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Marik Bast' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Reese Johnson' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Paige Thompson' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Remi Chen' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

-- Ballet Intensive enrollments
INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Hazel Vincent' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Paige Thompson' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Caralin Wilson' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Stella Anderson' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

-- Audition Prep enrollments
INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Everly Hazard' AND ct.CLASS_TYPE_CODE = 'AUD_PREP';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Larkin Mack' AND ct.CLASS_TYPE_CODE = 'AUD_PREP';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Reese Johnson' AND ct.CLASS_TYPE_CODE = 'AUD_PREP';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Meghan Davis' AND ct.CLASS_TYPE_CODE = 'AUD_PREP';

-- Master Intensive enrollments (advanced students only)
INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'MASTER_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ryann Foster' AND ct.CLASS_TYPE_CODE = 'MASTER_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Meghan Davis' AND ct.CLASS_TYPE_CODE = 'MASTER_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Stella Anderson' AND ct.CLASS_TYPE_CODE = 'MASTER_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Georgia White' AND ct.CLASS_TYPE_CODE = 'MASTER_INT';

COMMIT;
