-- Combined SQL script to create STUDIO_PRIVATE_LESSONS table
-- This script can be executed as a single statement via SQLclScript.sh

BEGIN
   -- Drop table if exists (Oracle syntax)
   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE STUDIO_PRIVATE_LESSONS';
   EXCEPTION
      WHEN OTHERS THEN
         IF SQLCODE != -942 THEN
            RAISE;
         END IF;
   END;

   -- Create the table
   EXECUTE IMMEDIATE '
   CREATE TABLE STUDIO_PRIVATE_LESSONS (
       LESSON_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       WEEK_START_DATE DATE NOT NULL,
       WEEK_IDENTIFIER VARCHAR2(50) NOT NULL,
       SHEET_NAME VARCHAR2(100) NOT NULL,
       TIME_SLOT VARCHAR2(10) NOT NULL,
       LESSON_DATA CLOB NOT NULL CHECK (LESSON_DATA IS JSON),
       FULL_WEEK_JSON CLOB NOT NULL CHECK (FULL_WEEK_JSON IS JSON),
       EXTRACTED_DATE DATE DEFAULT SYSDATE,
       CREATED_DATE DATE DEFAULT SYSDATE,
       MODIFIED_DATE DATE DEFAULT SYSDATE
   )';

   -- Create indexes
   EXECUTE IMMEDIATE 'CREATE INDEX idx_studio_private_lessons_week ON STUDIO_PRIVATE_LESSONS(week_identifier)';
   EXECUTE IMMEDIATE 'CREATE INDEX idx_studio_private_lessons_time ON STUDIO_PRIVATE_LESSONS(time_slot)';
   EXECUTE IMMEDIATE 'CREATE INDEX idx_studio_private_lessons_sheet ON STUDIO_PRIVATE_LESSONS(sheet_name)';

   -- Add comments
   EXECUTE IMMEDIATE 'COMMENT ON TABLE STUDIO_PRIVATE_LESSONS IS ''Store private lesson schedules extracted from Excel files''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_start_date IS ''Start date of the week (e.g., 2025-06-09)''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.week_identifier IS ''Unique identifier for the week (e.g., 2025-06-09-69-615)''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.sheet_name IS ''Excel sheet name (e.g., 69-615)''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.time_slot IS ''Time slot for the lessons''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.lesson_data IS ''JSON data containing all lessons for this time slot''';
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN STUDIO_PRIVATE_LESSONS.full_week_json IS ''Complete JSON object for the entire week schedule''';

   DBMS_OUTPUT.PUT_LINE('STUDIO_PRIVATE_LESSONS table created successfully');
END;
