-- Sample data for Studio Manager
-- Insert sample students
INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Everly Hazard', 'Jennifer', 'Hazard', 'jenhaz23@gmail.com', '555-0101', DATE '2016-10-25', 'Both', 'Very dedicated student', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Gemma Smith', 'Tia', 'Smith', 'TiaFSmith@gmail.com', '555-0102', DATE '2017-05-15', 'Both', 'Shows great potential', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Hazel Vincent', 'Jaclyn', 'Vincent', 'jaclynvincent17@gmail.com', '555-0103', DATE '2017-10-22', 'Both', 'Excellent technique', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Marik Bast', 'Amy', 'Bast', 'asbast5@gmail.com', '555-0104', DATE '2017-01-26', 'Both', 'Natural performer', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Larkin Mack', 'Allison', 'Mack', 'allison0143@gmail.com', '555-0105', DATE '2016-04-29', 'Both', 'Strong solo work', 'SYSTEM');

INSERT INTO STUDIO_STUDENTS (STUDENT_NAME, PARENT_FIRST_NAME, PARENT_LAST_NAME, CONTACT_EMAIL, CONTACT_PHONE, BIRTH_DATE, AUDITION_STATUS, NOTES, CREATED_BY)
VALUES ('Ronni Weiss', 'Adva', 'Weiss', 'Advaweiss@gmail.com', '555-0106', DATE '2010-07-28', 'Both', 'Senior level dancer', 'SYSTEM');

-- Enroll students in classes
-- Get class type IDs first and enroll students
INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Gemma Smith' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Marik Bast' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'BALLET_INT';

INSERT INTO STUDIO_STUDENT_CLASSES (STUDENT_ID, CLASS_TYPE_ID)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID 
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct 
WHERE s.STUDENT_NAME = 'Everly Hazard' AND ct.CLASS_TYPE_CODE = 'AUD_PREP';

-- Create a weekly schedule for current week
INSERT INTO STUDIO_WEEKLY_SCHEDULES (WEEK_START_DATE)
VALUES (TRUNC(SYSDATE, 'IW')); -- Current week start (Monday)

-- Add some schedule slots
INSERT INTO STUDIO_SCHEDULE_SLOTS (SCHEDULE_ID, STUDENT_ID, DAY_OF_WEEK, TIME_SLOT, LESSON_TYPE, NOTES)
SELECT ws.SCHEDULE_ID, s.STUDENT_ID, 'Friday', '15:45', 'Solo', 'Private lesson'
FROM STUDIO_WEEKLY_SCHEDULES ws, STUDIO_STUDENTS s
WHERE ws.WEEK_START_DATE = TRUNC(SYSDATE, 'IW') AND s.STUDENT_NAME = 'Hazel Vincent';

INSERT INTO STUDIO_SCHEDULE_SLOTS (SCHEDULE_ID, STUDENT_ID, DAY_OF_WEEK, TIME_SLOT, LESSON_TYPE, NOTES)
SELECT ws.SCHEDULE_ID, s.STUDENT_ID, 'Friday', '16:15', 'Solo', 'Private lesson'
FROM STUDIO_WEEKLY_SCHEDULES ws, STUDIO_STUDENTS s
WHERE ws.WEEK_START_DATE = TRUNC(SYSDATE, 'IW') AND s.STUDENT_NAME = 'Larkin Mack';

INSERT INTO STUDIO_SCHEDULE_SLOTS (SCHEDULE_ID, STUDENT_ID, DAY_OF_WEEK, TIME_SLOT, LESSON_TYPE, NOTES)
SELECT ws.SCHEDULE_ID, s.STUDENT_ID, 'Sunday', '15:30', 'Solo', 'Private lesson'
FROM STUDIO_WEEKLY_SCHEDULES ws, STUDIO_STUDENTS s
WHERE ws.WEEK_START_DATE = TRUNC(SYSDATE, 'IW') AND s.STUDENT_NAME = 'Larkin Mack';

INSERT INTO STUDIO_SCHEDULE_SLOTS (SCHEDULE_ID, STUDENT_ID, DAY_OF_WEEK, TIME_SLOT, LESSON_TYPE, NOTES)
SELECT ws.SCHEDULE_ID, s.STUDENT_ID, 'Thursday', '17:00', 'Choreography', 'Everly solo prep'
FROM STUDIO_WEEKLY_SCHEDULES ws, STUDIO_STUDENTS s
WHERE ws.WEEK_START_DATE = TRUNC(SYSDATE, 'IW') AND s.STUDENT_NAME = 'Everly Hazard';

-- Add some attendance records
INSERT INTO STUDIO_ATTENDANCE (STUDENT_ID, CLASS_TYPE_ID, ATTENDANCE_DATE, STATUS)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID, SYSDATE - 7, 'PRESENT'
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct
WHERE s.STUDENT_NAME = 'Gemma Smith' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_ATTENDANCE (STUDENT_ID, CLASS_TYPE_ID, ATTENDANCE_DATE, STATUS)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID, SYSDATE - 7, 'PRESENT'
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct
WHERE s.STUDENT_NAME = 'Marik Bast' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

INSERT INTO STUDIO_ATTENDANCE (STUDENT_ID, CLASS_TYPE_ID, ATTENDANCE_DATE, STATUS)
SELECT s.STUDENT_ID, ct.CLASS_TYPE_ID, SYSDATE - 7, 'LATE'
FROM STUDIO_STUDENTS s, STUDIO_CLASS_TYPES ct
WHERE s.STUDENT_NAME = 'Ronni Weiss' AND ct.CLASS_TYPE_CODE = 'TECH_INT';

COMMIT;
